// Logos

import EastLogo from "../assets/Conferences/East.png";
import WestLogo from "../assets/Conferences/West.png";

import SixersLogo from "../assets/Logos/76ers.png";
import SixersLogoLight from "../assets/Logos/76ersLight.png";
import BucksLogo from "../assets/Logos/Bucks.png";
import BullsLogo from "../assets/Logos/Bulls.png";
import CavaliersLogo from "../assets/Logos/Cavaliers.png";
import CelticsLogo from "../assets/Logos/Celtics.png";
import ClippersLogo from "../assets/Logos/Clippers.png";
import GrizzliesLogo from "../assets/Logos/Grizzlies.png";
import HawksLogo from "../assets/Logos/Hawks.png";
import HeatLogo from "../assets/Logos/Heat.png";
import HornetsLogo from "../assets/Logos/Hornets.png";
import JazzLogo from "../assets/Logos/Jazz.png";
import JazzLogoLight from "../assets/Logos/JazzLight.png";
import KingsLogo from "../assets/Logos/Kings.png";
import KnicksLogo from "../assets/Logos/Knicks.png";
import LakersLogo from "../assets/Logos/Lakers.png";
import MagicLogo from "../assets/Logos/Magic2.png";
import MavericksLogo from "../assets/Logos/Mavericks.png";
import NetsLogo from "../assets/Logos/Nets.png";
import NuggetsLogo from "../assets/Logos/Nuggets.png";
import PacersLogo from "../assets/Logos/Pacers.png";
import PelicansLogo from "../assets/Logos/Pelicans.png";
import PistonsLogo from "../assets/Logos/Pistons.png";
import RaptorsLogo from "../assets/Logos/Raptors.png";
import RaptorsLogoLight from "../assets/Logos/RaptorsLight.png";
import RocketsLogo from "../assets/Logos/Rockets.png";
import RocketsLogoLight from "../assets/Logos/RocketsLight.png";
import SpursLogo from "../assets/Logos/Spurs.png";
import SunsLogo from "../assets/Logos/Suns.png";
import ThunderLogo from "../assets/Logos/Thunder.png";
import TimberwolvesLogo from "../assets/Logos/Timberwolves.png";
import TrailBlazersLogo from "../assets/Logos/TrailBlazers.png";
import WarriorsLogo from "../assets/Logos/Warriors.png";
import WizardsLogo from "../assets/Logos/Wizards.png";

// Arenas
import BucksArena from "../assets/Arenas/BucksArena.webp";
import BullsArena from "../assets/Arenas/BullsArena.webp";
import CavaliersArena from "../assets/Arenas/CavaliersArena.webp";
import CelticsArena from "../assets/Arenas/CelticsArena.webp";
import ClippersArena from "../assets/Arenas/ClippersArena.webp";
import GrizzliesArena from "../assets/Arenas/GrizzliesArena.webp";
import HawksArena from "../assets/Arenas/HawksArena.webp";
import HeatArena from "../assets/Arenas/HeatArena.webp";
import HornetsArena from "../assets/Arenas/HornetsArena.webp";
import JazzArena from "../assets/Arenas/JazzArena.webp";
import KingsArena from "../assets/Arenas/KingsArena.webp";
import KnicksArena from "../assets/Arenas/KnicksArena.webp";
import LakersArena from "../assets/Arenas/LakersArena.webp";
import MagicArena from "../assets/Arenas/MagicArena.webp";
import MavericksArena from "../assets/Arenas/MavericksArena.webp";
import NetsArena from "../assets/Arenas/NetsArena.webp";
import NuggetsArena from "../assets/Arenas/NuggetsArena.webp";
import PacersArena from "../assets/Arenas/PacersArena.webp";
import PelicansArena from "../assets/Arenas/PelicansArena.webp";
import PistonsArena from "../assets/Arenas/PistonsArena.webp";
import RaptorsArena from "../assets/Arenas/RaptorsArena.webp";
import RocketsArena from "../assets/Arenas/RocketsArena.webp";
import SixersArena from "../assets/Arenas/SixersArena.webp";
import SpursArena from "../assets/Arenas/SpursArena.webp";
import SunsArena from "../assets/Arenas/SunsArena.webp";
import ThunderArena from "../assets/Arenas/ThunderArena.webp";
import TimberwolvesArena from "../assets/Arenas/TimberwolvesArena.webp";
import TrailBlazersArena from "../assets/Arenas/TrailBlazersArena.webp";
import WarriorsArena from "../assets/Arenas/WarriorsArena.webp";
import WizardsArena from "../assets/Arenas/WizardsArena.webp";

// Coach Images
import BucksCoach from "../assets/Coaches/BucksCoach.png";
import BullsCoach from "../assets/Coaches/BullsCoach.png";
import CavsCoach from "../assets/Coaches/CavsCoach.png";
import CelticsCoach from "../assets/Coaches/CelticsCoach.png";
import ClippersCoach from "../assets/Coaches/ClippersCoach.png";
import GrizzliesCoach from "../assets/Coaches/GrizzliesCoach.png";
import HawksCoach from "../assets/Coaches/HawksCoach.png";
import HeatCoach from "../assets/Coaches/HeatCoach.png";
import HornetsCoach from "../assets/Coaches/HornetsCoach.png";
import JazzCoach from "../assets/Coaches/JazzCoach.png";
import KingsCoach from "../assets/Coaches/KingsCoach.png";
import LakersCoach from "../assets/Coaches/LakersCoach.png";
import MagicCoach from "../assets/Coaches/MagicCoach.png";
import MavsCoach from "../assets/Coaches/MavsCoach.png";
import NetsCoach from "../assets/Coaches/NetsCoach.png";
import NuggetsCoach from "../assets/Coaches/NuggetsCoach.png";
import PacersCoach from "../assets/Coaches/PacersCoach.png";
import PelicansCoach from "../assets/Coaches/PelicansCoach.png";
import PistonsCoach from "../assets/Coaches/PistonsCoach.png";
import RaptorsCoach from "../assets/Coaches/RaptorsCoach.png";
import RocketsCoach from "../assets/Coaches/RocketsCoach.png";
import SixersCoach from "../assets/Coaches/SixersCoach.png";
import SpursCoach from "../assets/Coaches/SpursCoach.png";
import SunsCoach from "../assets/Coaches/SunsCoach.png";
import ThunderCoach from "../assets/Coaches/ThunderCoach.png";
import TimberwolvesCoach from "../assets/Coaches/TimberwolvesCoach.png";
import TrailBlazersCoach from "../assets/Coaches/TrailBlazersCoach.png";
import WarriorsCoach from "../assets/Coaches/WarriorsCoach.png";
import WizardsCoach from "../assets/Coaches/WizardsCoach.png";

export type Team = {
  id: string;
  fullName: string;
  name: string;
  code: string;
  logo: any;
  logoLight?: any; // optional light variant
  color: string;
  transparentColor: string;
  secondaryColor: string;
  arenaImage?: any;
  location?: string; // new field
  arenaName?: string;
  championships?: any;
  conferenceChampionships?: any;
  firstSeason?: string;
  allTimeRecord?: string;
  conferenceLogo?: any;
  conference?: string;
  latitude?: number;
  longitude?: number;
  address?: string;
  arenaCapacity?: string;
};

export const teams = [
  {
    id: "1",
    name: "Hawks",
    fullName: "Atlanta Hawks",
    code: "ATL",
    location: "Atlanta, GA",
    logo: HawksLogo,
    color: "rgba(224, 58, 62, 1)",
    transparentColor: "rgba(224, 58, 61, .8)",
    secondaryColor: "rgba(193, 211, 47, 1)",
    arenaImage: HawksArena,
    arenaName: "State Farm Arena",
    coach: "Quin Snyder",
    coachImage: HawksCoach,
    championships: [1958],
    conferenceChampionships: { Titles: [1960, 1961, 2015] },
    firstSeason: "1949",
    allTimeRecord: "2968-3053",
    conference: "Eastern",
    conferenceLogo: EastLogo,
    latitude: 33.7573,
    longitude: -84.3963,
    address: "1 State Farm Drive, Atlanta, GA 30303",
    arenaCapacity: "16,888",
  },
  {
    id: "2",
    name: "Celtics",
    fullName: "Boston Celtics",
    code: "BOS",
    location: "Boston, MA",
    logo: CelticsLogo,
    color: "rgba(0, 122, 51, 1)",
    transparentColor: "rgba(0, 122, 51, .8)",
    secondaryColor: "rgba(255, 255, 255, 1)",
    arenaImage: CelticsArena,
    arenaName: "TD Garden",
    coach: "Joe Mazzulla",
    championships: [
      1957, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1968, 1969, 1974,
      1976, 1981, 1984, 1986, 2008, 2024,
    ],
    conferenceChampionships: {
      Titles: [
        1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1968, 1969,
        1974, 1976, 1981, 1984, 1985, 1986, 1987, 2008, 2010, 2022, 2024,
      ],
    },
    firstSeason: "1949",
    allTimeRecord: "3695-2501",
    conference: "Eastern",
    conferenceLogo: EastLogo,
    latitude: 42.3662,
    longitude: -71.0621,
    address: "100 Legends Way, Boston, MA 02114",
    arenaCapacity: "18,624",
  },
  {
    id: "4",
    name: "Nets",
    fullName: "Brooklyn Nets",
    code: "BKN",
    location: "Brooklyn, NY",
    logo: NetsLogo,
    color: "rgba(0, 0, 0, 1)",
    transparentColor: "rgba(0, 0, 0, .8)",
    secondaryColor: "rgba(255, 255, 255, 1)",
    arenaImage: NetsArena,
    arenaName: "Barclays Center",
    coach: "Jordi Fernandez	",
    coachImage: NetsCoach,
    championships: [],
    conferenceChampionships: { Titles: [2002, 2003] },
    firstSeason: "1976",
    allTimeRecord: "1680-2270",
    conference: "Eastern",
    conferenceLogo: EastLogo,
    latitude: 40.6826,
    longitude: -73.9754,
    address: "620 Atlantic Avenue, Brooklyn, NY 11217",
    arenaCapacity: "17,732",
  },
  {
    id: "5",
    name: "Hornets",
    fullName: "Charlotte Hornets",
    code: "CHA",
    location: "Charlotte, NC",
    logo: HornetsLogo,
    color: "rgb(0, 120, 140)",
    transparentColor: "rgba(29, 17, 96, .8)",
    secondaryColor: "rgba(29, 17, 96, 1)",
    arenaImage: HornetsArena,
    arenaName: "Spectrum Center",
    coach: "Charles Lee",
    coachImage: HornetsCoach,
    championships: [],
    conferenceChampionships: [],
    firstSeason: "1988",
    allTimeRecord: "1193-1602",
    conference: "Eastern",
    conferenceLogo: EastLogo,
    latitude: 35.2251,
    longitude: -80.8392,
    address: "333 East Trade Street, Charlotte, NC 28202",
    arenaCapacity: "19,077",
  },
  {
    id: "6",
    name: "Bulls",
    fullName: "Chicago Bulls",
    code: "CHI",
    location: "Chicago, IL",
    logo: BullsLogo,
    color: "rgba(206, 17, 65, 1)",
    transparentColor: "rgba(206, 17, 65, .8)",
    secondaryColor: "rgba(0, 0, 0, 1)",
    arenaImage: BullsArena,
    arenaName: "United Center",
    coach: "Billy Donovan",
    coachImage: BullsCoach,
    championships: [1991, 1992, 1993, 1996, 1997, 1998],
    firstSeason: "1966",
    allTimeRecord: "2422-2340",
    conference: "Eastern",
    conferenceLogo: EastLogo,
    conferenceChampionships: { Titles: [1991, 1992, 1993, 1996, 1997, 1998] },
    latitude: 41.8807,
    longitude: -87.6742,
    address: "1901 West Madison Street, Chicago, IL 60612",
    arenaCapacity: "20,917",
  },
  {
    id: "7",
    name: "Cavaliers",
    fullName: "Cleveland Cavaliers",
    code: "CLE",
    location: "Cleveland, OH",
    logo: CavaliersLogo,
    color: "rgba(134, 0, 56, 1)",
    transparentColor: "rgba(134, 0, 56, .8)",
    secondaryColor: "rgba(253, 187, 48, 1)",
    arenaImage: CavaliersArena,
    arenaName: "Rocket Mortgage FieldHouse",
    coach: "Kenny Atkinson",
    coachImage: CavsCoach,
    championships: [2016],
    firstSeason: "1970",
    allTimeRecord: "2096-2339",
    conference: "Eastern",
    conferenceLogo: EastLogo,
    conferenceChampionships: { Titles: [2007, 2015, 2016, 2017, 2018] },
    latitude: 41.496,
    longitude: -81.6882,
    address: "1 Center Court, Cleveland, OH 44115",
    arenaCapacity: "19,432",
  },
  {
    id: "8",
    name: "Mavericks",
    fullName: "Dallas Mavericks",
    code: "DAL",
    location: "Dallas, TX",
    logo: MavericksLogo,
    color: "rgb(0, 83, 188)",
    transparentColor: "rgba(0, 83, 188, .8)",
    secondaryColor: "rgba(0, 0, 0, 1)",
    arenaImage: MavericksArena,
    arenaName: "American Airlines Center",
    coach: "Jason Kidd",
    coachImage: MavsCoach,
    championships: [2011],
    firstSeason: "1980",
    allTimeRecord: "1836-1789",
    conference: "Western",
    conferenceLogo: WestLogo,
    conferenceChampionships: { Titles: [2006, 2011, 2024] },
    latitude: 32.7905,
    longitude: -96.8103,
    address: "2500 Victory Avenue, Dallas, TX 75219",
    arenaCapacity: "19,200",
  },
  {
    id: "9",
    name: "Nuggets",
    fullName: "Denver Nuggets",
    code: "DEN",
    location: "Denver, CO",
    logo: NuggetsLogo,
    color: "rgba(13, 34, 64, 1)",
    transparentColor: "rgba(13, 34, 64, .8)",
    secondaryColor: "rgba(255, 198, 39, 1)",
    arenaImage: NuggetsArena,
    arenaName: "Ball Arena",
    coach: "David Adelman",
    coachImage: NuggetsCoach,
    championships: [2023],
    firstSeason: "1976",
    allTimeRecord: "2004-1947",
    conference: "Western",
    conferenceLogo: WestLogo,
    conferenceChampionships: { Titles: [2023] },
    latitude: 39.7487,
    longitude: -105.0077,
    address: "1000 Chopper Circle, Denver, CO 80204",
    arenaCapacity: "19,320",
  },
  {
    id: "10",
    name: "Pistons",
    fullName: "Detroit Pistons",
    code: "DET",
    location: "Detroit, MI",
    logo: PistonsLogo,
    color: "rgba(200, 16, 46, 1)",
    transparentColor: "rgba(29, 66, 138, .8)",
    secondaryColor: "rgba(29, 66, 138, 1)",
    arenaImage: PistonsArena,
    arenaName: "Little Caesars Arena",
    coach: "J.B. Bickerstaff",
    coachImage: PistonsCoach,
    championships: [1989, 1990, 2004],
    firstSeason: "1948",
    allTimeRecord: "2872-3210",
    conference: "Eastern",
    conferenceLogo: EastLogo,
    conferenceChampionships: {
      Titles: [1988, 1989, 1990, 2004, 2005, 2007, 2008],
      latitude: 42.6993,
      longitude: -83.247,
    },
    address: "2645 Woodward Avenue, Detroit, MI 48201",
    arenaCapacity: "20,491",
  },
  {
    id: "11",
    name: "Warriors",
    fullName: "Golden State Warriors",
    code: "GSW",
    location: "San Francisco, CA",
    logo: WarriorsLogo,
    color: "rgba(29, 66, 138, 1)",
    transparentColor: "rgba(29, 66, 138, .8)",
    secondaryColor: "rgba(255, 199, 44, 1)",
    arenaImage: WarriorsArena,
    arenaName: "Chase Center",
    coach: "Steve Kerr",
    coachImage: WarriorsCoach,
    championships: [1947, 1956, 1975, 2015, 2017, 2018, 2022],
    firstSeason: "1946",
    allTimeRecord: "3017-3168",
    conference: "Western",
    conferenceLogo: WestLogo,
    conferenceChampionships: {
      Titles: [
        1956, 1964, 1967, 1975, 1976, 2015, 2016, 2017, 2018, 2019, 2022,
      ],
    },
    latitude: 37.768,
    longitude: -122.3877,
    address: "1 Warriors Way, San Francisco, CA 94158",
    arenaCapacity: "18,064",
  },
  {
    id: "14",
    name: "Rockets",
    fullName: "Houston Rockets",
    code: "HOU",
    location: "Houston, TX",
    logo: RocketsLogo,
    logoLight: RocketsLogoLight,
    color: "rgba(206, 17, 65, 1)",
    transparentColor: "rgba(206, 17, 65, .8)",
    secondaryColor: "rgb(0, 0, 0)",
    arenaImage: RocketsArena,
    arenaName: "Toyota Center",
    coach: "Ime Udoka",
    coachImage: RocketsCoach,
    championships: [1994, 1995],
    firstSeason: "1967",
    allTimeRecord: "2421-2267",
    conference: "Western",
    conferenceLogo: WestLogo,
    conferenceChampionships: { Titles: [1981, 1986, 1994, 1995] },
    latitude: 29.7508,
    longitude: -95.3621,
    address: "1510 Polk Street, Houston, TX 77002",
    arenaCapacity: "18,055",
  },
  {
    id: "15",
    name: "Pacers",
    fullName: "Indiana Pacers",
    code: "IND",
    location: "Indianapolis, IN",
    logo: PacersLogo,
    color: "rgba(0, 45, 98, 1)",
    transparentColor: "rgba(0, 45, 98, .8)",
    secondaryColor: "rgba(255, 198, 39, 1)",
    arenaImage: PacersArena,
    arenaName: "Gainbridge Fieldhouse",
    coach: "Rick Carlisle",
    coachImage: PacersCoach,
    championships: [],
    firstSeason: "1976",
    allTimeRecord: "1980-1970",
    conference: "Eastern",
    conferenceLogo: EastLogo,
    conferenceChampionships: { Titles: [2000, 2025] },
    latitude: 39.764,
    longitude: -86.1559,
    address: "125 South Pennsylvania Street, Indianapolis, IN 46204",
    arenaCapacity: "17,923",
  },
  {
    id: "16",
    name: "Clippers",
    fullName: "Los Angeles Clippers",
    code: "LAC",
    location: "Los Angeles, CA",
    logo: ClippersLogo,
    color: "rgba(200, 16, 46, 1)",
    transparentColor: "rgba(200, 16, 46, .8)",
    secondaryColor: "rgba(29, 66, 148, 1)",
    arenaImage: ClippersArena,
    arenaName: "Intuit Dome",
    coach: "Tyronn Lue",
    coachImage: ClippersCoach,
    championships: [],
    firstSeason: "1970",
    allTimeRecord: "1893-2549",
    conference: "Western",
    conferenceLogo: WestLogo,
    conferenceChampionships: { Titles: [] },
    latitude: 34.043,
    longitude: -118.2673,
    address: "3930 W Century Blvd, Inglewood, CA 90303",
    arenaCapacity: "19,068",
  },
  {
    id: "17",
    name: "Lakers",
    fullName: "Los Angeles Lakers",
    code: "LAL",
    location: "Los Angeles, CA",
    logo: LakersLogo,
    color: "rgba(85, 37, 130, 1)",
    transparentColor: "rgba(85, 37, 130, .8)",
    secondaryColor: "rgba(253, 185, 39, 1)",
    arenaImage: LakersArena,
    arenaName: "Crypto.com Arena",
    coach: "JJ Redick",
    coachImage: LakersCoach,
    championships: [
      1949, 1950, 1952, 1953, 1954, 1972, 1980, 1982, 1985, 1987, 1988, 2000,
      2001, 2002, 2009, 2010, 2020,
    ],
    firstSeason: "1948",
    allTimeRecord: "3602-2487",
    conference: "Western",
    conferenceLogo: WestLogo,
    conferenceChampionships: {
      Titles: [
        1950, 1952, 1953, 1954, 1959, 1962, 1963, 1965, 1966, 1968, 1969, 1970,
        1972, 1973, 1980, 1982, 1983, 1984, 1985, 1987, 1988, 1989, 1991, 2000,
        2001, 2002, 2004, 2008, 2009, 2010, 2020, 2023,
      ],
    },
    latitude: 34.043,
    longitude: -118.2673,
    address: "1111 South Figueroa Street, Los Angeles, CA 90015",
    arenaCapacity: "19,068",
  },
  {
    id: "19",
    name: "Grizzlies",
    fullName: "Memphis Grizzlies",
    code: "MEM",
    location: "Memphis, TN",
    logo: GrizzliesLogo,
    color: "rgba(93, 118, 169, 1)",
    transparentColor: "rgba(93, 118, 169, .8)",
    secondaryColor: "rgba(18, 23, 63, 1)",
    arenaImage: GrizzliesArena,
    arenaName: "FedExForum",
    coach: "Tuomas Iisalo",
    coachImage: GrizzliesCoach,
    championships: [],
    firstSeason: "1995",
    allTimeRecord: "1046-1347",
    conference: "Western",
    conferenceLogo: WestLogo,
    conferenceChampionships: { Titles: [] },
    latitude: 35.1389,
    longitude: -90.0509,
    address: "191 Beale Street, Memphis, TN 38103",
    arenaCapacity: "18,119",
  },
  {
    id: "20",
    name: "Heat",
    fullName: "Miami Heat",
    code: "MIA",
    location: "Miami, FL",
    logo: HeatLogo,
    color: "rgba(152, 0, 46, 1)",
    transparentColor: "rgba(152, 0, 46, .8)",
    secondaryColor: "rgba(0, 0, 0, 1)",
    arenaImage: HeatArena,
    arenaName: "Kaseya Center",
    coach: "Erik Spoelstra",
    coachImage: HeatCoach,
    championships: [2006, 2012, 2013],
    firstSeason: "1988",
    allTimeRecord: "1558-1409",
    conference: "Eastern",
    conferenceLogo: EastLogo,
    conferenceChampionships: {
      Titles: [2006, 2011, 2012, 2013, 2014, 2020, 2023],
    },
    latitude: 25.7814,
    longitude: -80.187,
    address: "601 Biscayne Boulevard, Miami, FL 33132",
    arenaCapacity: "19,600",
  },
  {
    id: "21",
    name: "Bucks",
    fullName: "Milwaukee Bucks",
    code: "MIL",
    location: "Milwaukee, WI",
    logo: BucksLogo,
    color: "rgba(0, 71, 27, 1)",
    transparentColor: "rgba(0, 71, 27, .8)",
    secondaryColor: "rgba(240, 235, 210, 1)",
    arenaImage: BucksArena,
    arenaName: "Fiserv Forum",
    coach: "Doc Rivers",
    coachImage: BucksCoach,
    championships: [1971, 2021],
    firstSeason: "1968",
    allTimeRecord: "2437-2170",
    conference: "Eastern",
    conferenceLogo: EastLogo,
    conferenceChampionships: { Titles: [1971, 1974, 2021] },
    latitude: 43.0451,
    longitude: -87.9172,
    address: "1111 Vel R. Phillips Avenue, Milwaukee, WI 53203",
    arenaCapacity: "17,500",
  },
  {
    id: "22",
    name: "Timberwolves",
    fullName: "Minnesota Timberwolves",
    code: "MIN",
    location: "Minneapolis, MN",
    logo: TimberwolvesLogo,
    color: "rgba(12, 35, 64, 1)",
    transparentColor: "rgba(12, 35, 64, .8)",
    secondaryColor: "rgba(35, 97, 146, 1)",
    arenaImage: TimberwolvesArena,
    arenaName: "Target Center",
    coach: "Chris Finch",
    coachImage: TimberwolvesCoach,
    championships: [],
    firstSeason: "1989",
    allTimeRecord: "1196-1680",
    conference: "Western",
    conferenceLogo: WestLogo,
    conferenceChampionships: [],
    latitude: 44.9796,
    longitude: -93.276,
    address: "4 Pennsylvania Plaza, New York, NY 10001",
    arenaCapacity: "19,356",
  },

  {
    id: "23",
    name: "Pelicans",
    fullName: "New Orleans Pelicans",
    code: "NOP",
    location: "New Orleans, LA",
    logo: PelicansLogo,
    color: "rgba(0, 22, 65, 1)",
    transparentColor: "rgba(0, 22, 65, .8)",
    secondaryColor: "rgba(227, 24, 55, 1)",
    arenaImage: PelicansArena,
    arenaName: "Smoothie King Center",
    coach: "Willie Green",
    coachImage: PelicansCoach,
    championships: [],
    firstSeason: "2002",
    allTimeRecord: "852-998",
    conference: "Western",
    conferenceLogo: WestLogo,
    conferenceChampionships: { Titles: [] },
    latitude: 29.949,
    longitude: -90.081,
    address: "1501 Dave Dixon Drive, New Orleans, LA 70113",
    arenaCapacity: "16,867",
  },
  {
    id: "24",
    name: "Knicks",
    fullName: "New York Knicks",
    code: "NYK",
    location: "New York, NY",
    logo: KnicksLogo,
    color: "rgba(0, 107, 182, 1)",
    transparentColor: "rgba(0, 107, 182, .8)",
    secondaryColor: "rgba(245, 132, 38, 1)",
    arenaImage: KnicksArena,
    arenaName: "Madison Square Garden",
    coach: "Vacant",
    championships: [1970, 1973],
    firstSeason: "1946",
    allTimeRecord: "3025-3163",
    conference: "Eastern",
    conferenceLogo: EastLogo,
    conferenceChampionships: {
      Titles: [1951, 1952, 1953, 1970, 1972, 1973, 1994, 1999],
    },
    latitude: 40.7505,
    longitude: -73.9934,
    address: "4 Pennsylvania Plaza, New York, NY 10001",
    arenaCapacity: "19,812",
  },
  {
    id: "25",
    name: "Thunder",
    fullName: "Oklahoma City Thunder",
    code: "OKC",
    location: "Oklahoma City, OK",
    logo: ThunderLogo,
    color: "rgba(0, 125, 195, 1)",
    transparentColor: "rgba(0, 125, 195, .8)",
    secondaryColor: "rgba(239, 59, 36, 1)",
    arenaImage: ThunderArena,
    arenaName: "Paycom Center",
    coach: "Mark Daigneault",
    coachImage: ThunderCoach,
    championships: [1979, 2025],
    firstSeason: "1967",
    allTimeRecord: "2538-2150",
    conference: "Western",
    conferenceLogo: WestLogo,
    conferenceChampionships: { Titles: [1996, 2000, 2012, 2025] },
    latitude: 35.4633,
    longitude: -97.5151,
    address: "100 West Reno Avenue, Oklahoma City, OK 73102",
    arenaCapacity: "18,203",
  },

  {
    id: "26",
    name: "Magic",
    fullName: "Orlando Magic",
    code: "ORL",
    location: "Orlando, FL",
    logo: MagicLogo,
    color: "rgb(32, 80, 175)",
    transparentColor: "rgba(32, 79, 175, 0.8)",
    secondaryColor: "rgb(255, 255, 255)",
    arenaImage: MagicArena,
    arenaName: "Kia Center",
    coach: "Jamahl Mosley",
    coachImage: MagicCoach,
    championships: [],
    firstSeason: "1989",
    allTimeRecord: "1356-1529",
    conference: "Eastern",
    conferenceLogo: EastLogo,
    conferenceChampionships: { Titles: [1995, 2009] },
    latitude: 28.5392,
    longitude: -81.3839,
    address: "400 West Church Street, Orlando, FL 32801",
    arenaCapacity: "18,846",
  },
  {
    id: "27",
    name: "76ers",
    fullName: "Philadelphia 76ers",
    code: "PHI",
    location: "Philadelphia, PA",
    logo: SixersLogo,
    logoLight: SixersLogoLight,
    sixersLogoLight: SixersLogoLight,
    color: "rgba(0, 43, 92, 1)",
    transparentColor: "rgba(0, 107, 182, .8)",
    secondaryColor: "rgb(255, 255, 255)",
    arenaImage: SixersArena,
    arenaName: "Wells Fargo Arena",
    coach: "Nick Nurse",
    coachImage: SixersCoach,
    championships: [1955, 1967, 1983],
    firstSeason: "1949",
    allTimeRecord: "3126-2898",
    conference: "Eastern",
    conferenceLogo: EastLogo,
    conferenceChampionships: {
      Titles: [1950, 1954, 1955, 1965, 1967, 1977, 1980, 1982, 1983],
    },
    latitude: 39.9012,
    longitude: -75.172,
    address: "3601 South Broad Street, Philadelphia, PA 19148",
    arenaCapacity: "20,478",
  },
  {
    id: "28",
    name: "Suns",
    fullName: "Phoenix Suns",
    code: "PHX",
    location: "Phoenix, AZ",
    logo: SunsLogo,
    color: "rgba(229, 96, 32, 1)",
    transparentColor: "rgba(29, 17, 96, .8)",
    secondaryColor: "rgba(229, 96, 32, 1)",
    arenaImage: SunsArena,
    arenaName: "Footprint Center",
    coach: "Jordan Ott",
    coachImage: SunsCoach,
    championships: [],
    firstSeason: "1968",
    allTimeRecord: "2465-2142",
    conference: "Western",
    conferenceLogo: WestLogo,
    conferenceChampionships: { Titles: [1976, 1993, 2021] },
    latitude: 33.4452,
    longitude: -112.0712,
    address: "201 East Jefferson Street, Phoenix, AZ 85004",
    arenaCapacity: "18,422",
  },
  {
    id: "29",
    name: "Trail Blazers",
    fullName: "Portland Trail Blazers",
    code: "POR",
    location: "Portland, OR",
    logo: TrailBlazersLogo,
    color: "rgba(224, 58, 62, 1)",
    transparentColor: "rgba(224, 58, 62, .8)",
    secondaryColor: "rgba(0, 0, 0, 1)",
    arenaImage: TrailBlazersArena,
    arenaName: "Moda Center",
    coach: "Chauncey Billups",
    coachImage: TrailBlazersCoach,
    championships: [1977],
    firstSeason: "1970",
    allTimeRecord: "2328-2116",
    conference: "Western",
    conferenceLogo: WestLogo,
    conferenceChampionships: { Titles: [1977, 1990, 1992] },
    latitude: 45.5316,
    longitude: -122.6668,
    address: "1 North Center Court Street, Portland, OR 97227",
    arenaCapacity: "19,441",
  },
  {
    id: "30",
    name: "Kings",
    fullName: "Sacramento Kings",
    code: "SAC",
    location: "Sacramento, CA",
    logo: KingsLogo,
    color: "rgba(91, 43, 130, 1)",
    transparentColor: "rgba(99, 113, 122, .8)",
    secondaryColor: "rgba(99, 113, 122, 1)",
    arenaImage: KingsArena,
    arenaName: "Golden 1 Center",
    coach: "Doug Christie",
    coachImage: KingsCoach,
    championships: [1951],
    firstSeason: "1948",
    allTimeRecord: "2788-3300",
    conference: "Western",
    conferenceLogo: WestLogo,
    conferenceChampionships: { Titles: [1951] },
    latitude: 38.5807,
    longitude: -121.4994,
    address: "500 David J Stern Walk, Sacramento, CA 95814",
    arenaCapacity: "17,608",
  },
  {
    id: "31",
    name: "Spurs",
    fullName: "San Antonio Spurs",
    code: "SAS",
    location: "San Antonio, TX",
    logo: SpursLogo,
    color: "rgb(0, 0, 0)",
    transparentColor: "rgba(0, 0, 0, 0.8)",
    secondaryColor: "rgb(0, 0, 0)",
    arenaImage: SpursArena,
    arenaName: "Frost Bank Arena",
    coach: "Mitch Johnson",
    coachImage: SpursCoach,
    championships: [1999, 2003, 2005, 2007, 2014],
    firstSeason: "1976",
    allTimeRecord: "2339-1610",
    conference: "Western",
    conferenceLogo: WestLogo,
    conferenceChampionships: { Titles: [1999, 2003, 2005, 2007, 2013, 2014] },
    latitude: 29.427,
    longitude: -98.4378,
    address: "1 AT&T Center Parkway, San Antonio, TX 78219",
    arenaCapacity: "18,418",
  },
  {
    id: "38",
    name: "Raptors",
    fullName: "Toronto Raptors",
    code: "TOR",
    location: "Toronto, ON",
    logo: RaptorsLogo,
    logoLight: RaptorsLogoLight,
    color: "rgb(0, 0, 0)",
    transparentColor: "rgba(206, 17, 65, .8)",
    secondaryColor: "rgb(255, 255, 255)",
    arenaImage: RaptorsArena,
    arenaName: "Scotiabank Arena",
    coach: "Darko Rajaković",
    coachImage: RaptorsCoach,
    championships: [2019],
    firstSeason: "1995",
    allTimeRecord: "1126-1266",
    conference: "Eastern",
    conferenceLogo: EastLogo,
    conferenceChampionships: { Titles: [2019] },
    latitude: 43.6435,
    longitude: -79.3791,
    address: "40 Bay Street, Toronto, ON M5J 2X2, Canada",
    arenaCapacity: "19,800",
  },
  {
    id: "40",
    name: "Jazz",
    fullName: "Utah Jazz",
    code: "UTA",
    location: "Salt Lake City, UT",
    logo: JazzLogo,
    logoLight: JazzLogoLight,
    color: "rgb(62, 38, 128)",
    transparentColor: "rgba(0, 0, 0, .8)",
    secondaryColor: "rgb(62, 38, 128)",
    arenaImage: JazzArena,
    arenaName: "Delta Center",
    coach: "Will Hardy",
    coachImage: JazzCoach,
    championships: [],
    firstSeason: "1974",
    allTimeRecord: "2194-1920",
    conference: "Western",
    conferenceLogo: WestLogo,
    conferenceChampionships: { Titles: [1997, 1998] },
    latitude: 40.768,
    longitude: -111.9011,
    address: "301 South Temple, Salt Lake City, UT 84101",
    arenaCapacity: "18,306",
  },
  {
    id: "41",
    name: "Wizards",
    fullName: "Washington Wizards",
    code: "WAS",
    location: "Washington, DC",
    logo: WizardsLogo,
    color: "rgba(0, 43, 92, 1)",
    transparentColor: "rgba(0, 43, 92, .8)",
    secondaryColor: "rgba(227, 24, 55, 1)",
    arenaImage: WizardsArena,
    arenaName: "Capital One Arena",
    coach: "Brian Keefe",
    coachImage: WizardsCoach,
    championships: [1978],
    firstSeason: "1961",
    allTimeRecord: "2290-2879",
    conference: "Eastern",
    conferenceLogo: EastLogo,
    conferenceChampionships: { Titles: [1971, 1975, 1978, 1979] },
    latitude: 38.898,
    longitude: -77.0209,
    address: "601 F Street NW, Washington, DC 20004",
    arenaCapacity: "20,356",
  },
];

// ... all other imports

export const coachImages: { [key: string]: any } = {
  BucksCoach,
  BullsCoach,
  CavsCoach,
  CelticsCoach,
  ClippersCoach,
  GrizzliesCoach,
  HawksCoach,
  HeatCoach,
  HornetsCoach,
  JazzCoach,
  KingsCoach,
  LakersCoach,
  MagicCoach,
  MavsCoach,
  NetsCoach,
  NuggetsCoach,
  PacersCoach,
  PelicansCoach,
  PistonsCoach,
  RaptorsCoach,
  RocketsCoach,
  SixersCoach,
  SpursCoach,
  SunsCoach,
  ThunderCoach,
  TimberwolvesCoach,
  TrailBlazersCoach,
  WarriorsCoach,
  WizardsCoach,
};

// /constants/teams.ts
export const logoMap: Record<string, any> = {
  SixersLogo,
  SixersLogoLight,
  BucksLogo,
  BullsLogo,
  CavaliersLogo,
  CelticsLogo,
  ClippersLogo,
  GrizzliesLogo,
  HawksLogo,
  HeatLogo,
  HornetsLogo,
  JazzLogo,
  JazzLogoLight,
  KingsLogo,
  KnicksLogo,
  LakersLogo,
  MagicLogo,
  MavericksLogo,
  NetsLogo,
  NuggetsLogo,
  PacersLogo,
  PelicansLogo,
  PistonsLogo,
  RaptorsLogo,
  RaptorsLogoLight,
  RocketsLogo,
  RocketsLogoLight,
  SpursLogo,
  SunsLogo,
  ThunderLogo,
  TimberwolvesLogo,
  TrailBlazersLogo,
  WarriorsLogo,
  WizardsLogo,
};

export const teamsById: Record<string, Team> = teams.reduce((map, team) => {
  map[team.id] = team;
  return map;
}, {} as Record<string, Team>);
