import AsyncStorage from "@react-native-async-storage/async-storage";
import { useEffect, useState } from "react";

type Highlight = {
  videoId: string;
  title: string;
  publishedAt: string;
  thumbnail: string;
  views: number;
};

// Utility to decode HTML entities
function decodeHTMLEntities(text: string): string {
  return text
    .replace(/&#(\d+);/g, (_, dec) => String.fromCharCode(dec))
    .replace(/&quot;/g, '"')
    .replace(/&amp;/g, "&")
    .replace(/&apos;/g, "'")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">");
}

// Known acronyms that should remain capitalized
// Known acronyms
const ACRONYMS = new Set([
  "NBA",
  "WNBA",
  "FIBA",
  "USA",
  "DPOY",
  "AD",
  "KD",
  "JR",
  "Jr.",
  "OKC",
  "LAL",
  "BOS",
  "PHX",
  "SAS",
  "DAL",
  "HOU",
  "MEM",
  "UTA",
  "ATL",
  "CHI",
  "CLE",  
  "DET",
  "IND",
  "MIA",
  "NYK",
  "ORL",
  "PHI",
  "TOR",
  "BKN",
  "WAS",
  "MIL",
  "LAC",
  "NOP",
  "POR",
  "SAC",
  "GSW",
  "3PT",
  "SGA",
  "MVP",
  "CP3",
  "PF",
  "SF",
  "C",
  "PG",
  "SG",
]);

// NBA Teams and Cities to preserve case
const PROPER_NOUNS = new Set([
  // Teams
  "Lakers",
  "Celtics",
  "Warriors",
  "Nuggets",
  "Clippers",
  "Suns",
  "Kings",
  "Grizzlies",
  "Spurs",
  "Mavericks",
  "Timberwolves",
  "Rockets",
  "Pelicans",
  "Thunder",
  "Jazz",
  "Bucks",
  "Heat",
  "Knicks",
  "Sixers",
  "76ers",
  "Cavaliers",
  "Bulls",
  "Pistons",
  "Pacers",
  "Hawks",
  "Hornets",
  "Magic",
  "Wizards",
  "Raptors",
  "Nets",

  // Cities
  "Los Angeles",
  "Boston",
  "Golden State",
  "Denver",
  "Phoenix",
  "Sacramento",
  "Memphis",
  "San Antonio",
  "Dallas",
  "Minnesota",
  "Houston",
  "New Orleans",
  "Oklahoma City",
  "Utah",
  "Milwaukee",
  "Miami",
  "New York",
  "Philadelphia",
  "Cleveland",
  "Chicago",
  "Detroit",
  "Indiana",
  "Atlanta",
  "Charlotte",
  "Orlando",
  "Washington",
  "Toronto",
  "Brooklyn",

  //Names
  "Bol Bol",
  "TyTy Washington Jr.",
  "Jalen Bridges",
  "Damion Lee",
  "Ryan Dunn",
  "Oso Ighodaro",
  "M. Wood",
  "Bradley Beal",
  "Mason Plumlee",
  "Devonte' Graham",
  "Deandre Ayton",
  "Robert Williams III",
  "Deni Avdija",
  "Dalano Banton",
  "Scoot Henderson",
  "Bryce McGowens",
  "Jabari Walker",
  "Justin Minaya",
  "Toumani Camara",
  "Kris Murray",
  "Orlando Robinson",
  "Keon Ellis",
  "Moritz Wagner",
  "Jalen McDaniels",
  "Mason Jones",
  "Terry Taylor",
  "Skal Labissiere",
  "Markelle Fultz",
  "Sidy Cissoko",
  "R. Rupert",
  "Donovan Clingan",
  "Jerami Grant",
  "Taze Moore",
  "Trey Lyles",
  "De'Aaron Fox",
  "Malik Monk",
  "Reggie Jackson",
  "Joel Embiid",
  "Tyus Jones",
  "Frank Kaminsky",
  "Keegan Murray",
  "Jaden Springer",
  "Colby Jones",
  "Paul George",
  "Royce O'Neale",
  "Grayson Allen",
  "Mamadi Diakite",
  "Devin Carter",
  "Immanuel Quickley",
  "Stephon Castle",
  "Jarrett Culver",
  "Charles Bassey",
  "Isaiah Crawford",
  "Boogie Ellis",
  "Harrison Ingram",
  "Devin Vassell",
  "Alex Ducas",
  "David Duke Jr.",
  "Isaac Jones",
  "Bones Hyland",
  "Ochai Agbaji",
  "Scottie Barnes",
  "Jonas Valanciunas",
  "Eric Gordon",
  "DeMar DeRozan",
  "Kenrich Williams",
  "Sandro Mamukelashvili",
  "Julian Champagnie",
  "Isaiah Hartenstein",
  "Riley Minix",
  "Bismack Biyombo",
  "Malaki Branham",
  "Jae Crowder",
  "Blake Wesley",
  "Jeremy Sochan",
  "Harrison Barnes",
  "Victor Wembanyama",
  "Victor",
"Williams",
"Williamson",
"Jay Bilas",
  "Wembanyama",
  "Doug McDermott",
  "Jakob Poeltl",
  "Chris Boucher",
  "RJ Barrett",
  "Jahmi'us Ramsey",
  "Adam Flagler",
  "D'Angelo Russell",
  "Keldon Johnson",
  "Luguentz Dort",
  "Cason Wallace",
  "Mouhamed Gueye",
  "Donte DiVincenzo",
  "Max Fiedler",
  "Jordan McLaughlin",
  "Zion Williamson",
  "Matisse Thybulle",
  "D.J. Carton",
  "Goga Bitadze",
  "Terry Rozier",
  "CJ McCollum",
  "Ulrich Chomche",
  "Gradey Dick",
  "Luka Doncic",
  "Duop Reath",
  "Daniel Theis",
  "Domantas Sabonis",
  "A.J. Lawson",
  "Kylor Kelley",
  "Colin Castleton",
  "Brodric Thomas",
  "John Konchar",
  "Elfrid Payton",
  "N'Faly Dante",
  "Shaedon Sharpe",
  "Kevin Durant",
  "Dalton Knecht",
  "Enrique Freeman",
  "Monte Morris",
  "Collin Gillespie",
  "Kyle Lowry",
  "Jimmy Butler",
  "Andre Drummond",
  "Devin Booker",
  "Jamison Battle",
  "Anfernee Simons",
  "Jacob Toppin",
  "Jonathan Mogbo",
  "T.J. Warren",
  "Zaccharie Risacher",
  "Bogdan Bogdanovic",
  "Dennis Schröder",
  "Lauri Markkanen",
  "John Collins",
  "Johnny Juzang",
  "Alex Sarr",
  "Collin Sexton",
  "Hunter Tyson",
  "Russell Westbrook",
  "Jason Preston",
  "Micah Potter",
  "Walker Kessler",
  "Keyonte George",
  "Jordan Clarkson",
  "Malcolm Brogdon",
  "Jordan Poole",
  "Kira Lewis Jr.",
  "Anthony Gill",
  "Justin Champagnie",
  "Corey Kispert",
  "Johnny Davis",
  "Bilal Coulibaly",
  "Mitchell Robinson",
  "Jordan Tucker",
  "Jamal Shead",
  "Taylor Hendricks",
  "Brice Sensabaugh",
  "Isaiah Collier",
  "Kyle Filipowski",
  "Cody Williams",
  "T. Vukcevic",
  "Bub Carrington",
  "Kyshawn George",
  "T. Funk",
  "Ja'Kobe Walter",
  "Garrett Temple",
  "Cormac Ryan",
  "Tyler Smith",
  "Walter Clayton Jr.",
  "Dylan Harper",
  "VJ Edgecombe",
  "Kon Knueppel",
  "Ace Bailey",
  "Tre Johnson",
  "Jeremiah Fears",
  "Egor Demin",
  "Collin Murray-Boyles",
  "Khaman Maluach",
  "Joan Beringer",
  "Cedric Coward",
  "Noa Essengue",
  "Derik Queen",
  "Carter Bryant",
  "Thomas Sorber",
  "Yang Hansen",
  "Nolan Traoré",
  "Kasparas Jakučionis",
  "Will Riley",
  "Drake Powell",
  "Kam Jones",
  "Nique Clifford",
  "Jase Richardson",
  "Ben Saraf",
  "Danny Wolf",
  "Hugo González",
  "Liam McNeeley",
  "Yanic Konan Niederhauser",
  "Rasheer Fleming",
  "Noah Penda",
  "Sion James",
  "Ryan Kalkbrenner",
  "Johni Broome",
  "Cooper Flagg",
  "Chaz Lanier",
  "Alijah Martin",
  "Micah Peavy",
  "Koby Brea",
  "Maxime Raynaud",
  "Jamir Watkins",
  "Brooks Barnhizer",
  "Rocco Zikarsky",
  "Amari Williams",
  "Bogoljub Marković",
  "Javon Small",
  "Tyrese Proctor",
  "Kobe Sanders",
  "Mohamed Diawara",
  "Alex Toohey",
  "Adou Thiero",
  "John Tonje",
  "Taelon Peter",
  "Lachlan Olbrich",
  "Max Shulga",
  "Saliou Niang",
  "Jahmai Mashack",
  "Will Richard",
  "Asa Newell",
  "Dennis Smith Jr.",
  "Malachi Flynn",
  "Tidjane Salaun",
  "Dorian Finney-Smith",
  "Ethan Thompson",
  "Al Horford",
  "Kristaps Porzingis",
  "Luke Kornet",
  "Jordan Walsh",
  "Baylor Scheierman",
  "Jayson Tatum",
  "Larry Nance Jr.",
  "Drew Peterson",
  "Nic Claxton",
  "Trae Young",
  "Ziaire Williams",
  "Onyeka Okongwu",
  "Day'Ron Sharpe",
  "Jalen Johnson",
  "Cameron Johnson",
  "Keon Johnson",
  "Noah Clowney",
  "Kevon Harris",
  "Xavier Tillman",
  "Killian Hayes",
  "K.J. Simpson",
  "Mark Williams",
  "Ajay Mitchell",
  "Duane Washington Jr.",
  "Isaiah Wong",
  "Keyontae Johnson",
  "Trendon Watford",
  "Moussa Diabate",
  "Tyson Etienne",
  "Daniel Gafford",
  "Jalen Wilson",
  "Kendall Brown",
  "Dariq Whitehead",
  "Tyrese Martin",
  "Cam Thomas",
  "Terance Mann",
  "Dyson Daniels",
  "Shake Milton",
  "Dominick Barlow",
  "Anton Watson",
  "LaMelo Ball",
  "Jared Rhoden",
  "Kobe Bufkin",
  "Seth Lundy",
  "Harry Giles III",
  "Nikola Jokic",
  "Malik Beasley",
  "Jabari Smith Jr.",
  "David Roddy",
  "Dereck Lively II",
  "Jeenathan Williams",
  "Amen Thompson",
  "Markquis Nowell",
  "Dante Exum",
  "Markieff Morris",
  "Naji Marshall",
  "Kessler Edwards",
  "Jaden Hardy",
  "Jazian Gortman",
  "Spencer Dinwiddie",
  "Jamarion Sharp",
  "Peyton Watson",
  "Jalen Pickett",
  "Julian Strawther",
  "Charles Bediako",
  "PJ Hall",
  "Dwight Powell",
  "Zeke Nnaji",
  "Jalen Green",
  "Jaylen Brown",
  "De'Anthony Melton",
  "Klay Thompson",
  "Gary Payton II",
  "Spencer Jones",
  "W. Richardson",
  "Aaron Gordon",
  "Jalen Duren",
  "Ausar Thompson",
  "Jonathan Kuminga",
  "Pat Spencer",
  "Ronald Holland II",
  "Jaden Ivey",
  "Dereon Seabron",
  "Simone Fontecchio",
  "A. Estrada",
  "Lindy Waters III",
  "Aaron Holiday",
  "Jack McVeigh",
  "Jock Landale",
  "Alperen Sengun",
  "DeAndre Jordan",
  "Bobi Klintman",
  "Josh Okogie",
  "Nate Darling",
  "Reed Sheppard",
  "Steven Adams",
  "Pascal Siakam",
  "Kobe Brown",
  "E. Harkless",
  "Charlie Brown Jr.",
  "B. Hinson",
  "Tony Bradley",
  "Jeff Green",
  "Patty Mills",
  "Jaylen Martin",
  "Kawhi Leonard",
  "Rui Hachimura",
  "Obi Toppin",
  "Jordan Miller",
  "Trentyn Flowers",
  "Jaylen Wells",
  "Amari Bailey",
  "Jamie Jr. Jaquez",
  "Isaiah Jackson",
  "Bennedict Mathurin",
  "JD Davison",
  "Kevon Looney",
  "Moses Moody",
  "Trayce JacksonDavis",
  "Jackson Rowe",
  "Kevin Huerter",
  "Coby White",
  "Ron Harper Jr.",
  "Jevon Carter",
  "Zach LaVine",
  "Cody Martin",
  "Paul Reed",
  "Yongxi Cui",
  "Ben Sheppard",
  "Zach Collins",
  "Chris Duarte",
  "Miles Bridges",
  "Drew Timme",
  "James Wiseman",
  "DaQuan Jeffries",
  "Q. Post",
  "Talen Horton-Tucker",
  "Patrick Williams",
  "Ben Simmons",
  "Matas Buzelis",
  "Tre Jones",
  "Bruno Fernando",
  "Ty Jerome",
  "Adama Sanogo",
  "DJ Steward",
  "Jalen Smith",
  "Donovan Mitchell",
  "Saddiq Bey",
  "Kentavious Caldwell-Pope",
  "Svi Mykhailiuk",
  "Jahmir Young",
  "Max Strus",
  "Jarrett Allen",
  "Zhaire Smith",
  "Emanuel Miller",
  "AJ Griffin",
  "Tosan Evbuomwan",
  "Seth Curry",
  "Josh Giddey",
  "Lonzo Ball",
  "Nathan Mensah",
  "Reece Beekman",
  "Dylan Windler",
  "Maxwell Lewis",
  "E.J. Liddell",
  "Onuralp Bitim",
  "Kenneth Lofton Jr.",
  "Isaac Okoro",
  "JT Thor",
  "Evan Mobley",
  "Chris Paul",
  "Dean Wade",
  "Oscar Tshiebwe",
  "Richaun Holmes",
  "Sam Merrill",
  "Justin Holiday",
  "Jules Bernard",
  "Jacob Gilyard",
  "Emoni Bates",
  "Craig Porter Jr.",
  "Luke Travers",
  "Jaylon Tyson",
  "Tristan Thompson",
  "P.J. Washington",
  "Javonte Green",
  "Caleb Martin",
  "Gabe Vincent",
  "Torrey Craig",
  "Jrue Holiday",
  "Ayo Dosunmu",
  "Julian Phillips",
  "Taj Gibson",
  "Michael Porter Jr.",
  "Tobias Harris",
  "Nicolas Batum",
  "De'Andre Hunter",
  "Dalen Terry",
  "Neemias Queta",
  "Andrew Funk",
  "Vit Krejčí",
  "Brandon Miller",
  "Georges Niang",
  "Garrison Mathews",
  "Trey Alexander",
  "Kyrie Irving",
  "Jamal Murray",
  "Javante McCoy",
  "Marcus Garrett",
  "Clint Capela",
  "Payton Pritchard",
  "Daeqwon Plowden",
  "Sam Hauser",
  "Derrick White",
  "Isaiah Stewart",
  "Cade Cunningham",
  "Dmytro Skapintsev",
  "Grant Williams",
  "Damion Baugh",
  "Wendell Moore Jr.",
  "Olivier-Maxence Prosper",
  "Brandon Williams",
  "Nick Smith Jr.",
  "Darius Garland",
  "Kai Jones",
  "Dario Šarić",
  "Christian Braun",
  "Drew Eubanks",
  "Vlatko Čančar",
  "Gabe McGlothan",
  "Tre Mann",
  "Josh Green",
  "Buddy Hield",
  "Dillon Brooks",
  "Keaton Wallace",
  "Tyrese Haliburton",
  "Cam Whitmore",
  "Nassir Little",
  "Aaron Nesmith",
  "Fred VanVleet",
  "Gui Santos",
  "Norman Powell",
  "Marcus Sasser",
  "Damian Lillard",
  "Quenton Jackson",
  "Nate Hinton",
  "Johnny Furphy",
  "Kris Dunn",
  "Brandon Boston Jr.",
  "Daniss Jenkins",
  "Samardo Samuels",
  "Brandin Podziemski",
  "Kevin Knox II",
  "Caris LeVert",
  "Myles Turner",
  "Andrew Nembhard",
  "Tim Hardaway Jr.",
  "Ivica Zubac",
  "Jae'Sean Tate",
  "Tari Eason",
  "Jarace Walker",
  "Nikola Vucevic",
  "Stephen Curry",
  "Draymond Green",
  "James Johnson",
  "T.J. McConnell",
  "Cole Swider",
  "EJ Harkless",
  "Cam Christie",
  "Patrick Baldwin Jr.",
  "Braxton Key",
  "RayJ Dennis",
  "Tolu Smith",
  "Miye Oni",
  "Jay Huff",
  "Luke Kennard",
  "Anthony Davis",
  "Jaren Jackson Jr.",
  "Gary Trent Jr.",
  "Desmond Bane",
  "GG Jackson",
  "Zach Edey",
  "Jalen Hood-Schifino",
  "Cam Spencer",
  "M. Pereira",
  "Austin Reaves",
  "Jordan Goodwin",
  "Cam Reddish",
  "Miles Norris",
  "Brandon Clarke",
  "Christian Koloko",
  "Marvin Bagley III",
  "Kevin Porter Jr.",
  "Amir Coffey",
  "Jaxson Hayes",
  "Alondes Williams",
  "Derrick Jones Jr.",
  "Santi Aldama",
  "Lamar Stevens",
  "Liam Robbins",
  "Armando Bacot",
  "Yuki Kawamura",
  "Bronny James",
  "Andre Jr. Jackson",
  "Jake LaRavia",
  "Vince Williams Jr.",
  "Ja Morant",
  "Alex Len",
  "Max Christie",
  "Jarred Vanderbilt",
  "James Harden",
  "Maxi Kleber",
  "LeBron James",
  "Scotty Pippen Jr.",
  "Armel Traore",
  "Quincy Olivari",
  "Kyle Kuzma",
  "Marcus Smart",
  "Josh Richardson",
  "Josh Christopher",
  "Giannis Antetokounmpo",
  "Karl-Anthony Towns",
  "Caleb Daniels",
  "Taurean Prince",
  "Kevin Love",
  "Bam Adebayo",
  "Alec Burks",
  "Kyle Anderson",
  "Ryan Rollins",
  "A.J. Green",
  "Chris Livingston",
  "James Akinjo",
  "P.J. Dozier",
  "AJ Johnson",
  "Khris Middleton",
  "Tyler Smith",
  "Brook Lopez",
  "Josh Minott",
  "Rob Dillingham",
  "Terence Davis",
  "Thomas Bryant",
  "Isaiah Stevens",
  "Stanley Umude",
  "Kel'el Ware",
  "Mike Conley",
  "Anzejs Pasecniks",
  "Trhae Mitchell",
  "Delon Wright",
  "Davion Mitchell",
  "Dru Smith",
  "Nikola Jovic",
  "Keshad Johnson",
  "Pelle Larsson",
  "Zyon Pullin",
  "Bobby Portis",
  "Keita Bates-Diop",
  "Jamaree Bouyea",
  "Andrew Wiggins",
  "Duncan Robinson",
  "Haywood Highsmith",
  "Tyler Herro",
  "Pat Connaughton",
  "Bruce Brown",
  "Mo Bamba",
  "MarJon Beauchamp",
  "Jaylen Clark",
  "Joe Ingles",
  "Yves Missi",
  "K. Brooks",
  "Branden Carlson",
  "Kelly Olynyk",
  "Naz Reid",
  "Trey Murphy III",
  "Dillon Jones",
  "O.G. Anunoby",
  "Josh Hart",
  "Anthony Edwards",
  "Jaden McDaniels",
  "Daishen Nix",
  "Luka Garza",
  "Jesse Edwards",
  "Jaylen Nowell",
  "Jericho Sims",
  "Antonio Reeves",
  "J Oduro",
  "Ariel Hukporti",
  "Matt Ryan",
  "Jeremiah Robinson-Earl",
  "Julius Randle",
  "Terrence Jr. Shannon",
  "Herbert Jones",
  "Jalen Crutcher",
  "Jose Alvarado",
  "Malcolm Hill",
  "Karlo Matkovic",
  "Jamal Cain",
  "Jordan Hawkins",
  "Trey Jemison",
  "Rudy Gobert",
  "Leonard Miller",
  "Tristen Newton",
  "Eugene Omoruyi",
  "Brandon Ingram",
  "Dejounte Murray",
  "Nickeil Alexander-Walker",
  "Jalen Williams",
  "Chet Holmgren",
  "Miles McBride",
  "Miller Kopp",
  "Franz Wagner",
  "Jalen Suggs",
  "Jalen Brunson",
  "Jaylin Williams",
  "Jared Butler",
  "Mac McClung",
  "Jeff Dowtin",
  "P.J. Tucker",
  "Lester Quinones",
  "Paolo Banchero",
  "Moses Brown",
  "Tyrese Maxey",
  "Landry Shamet",
  "Quentin Grimes",
  "Javonte Smart",
  "Wendell Carter Jr.",
  "Chuma Okeke",
  "Ricky IV Council",
  "A. Reese",
  "Alex Caruso",
  "Malevy Leons",
  "Jonathan Isaac",
  "Cameron Payne",
  "Cole Anthony",
  "Trevelin Queen",
  "Pacome Dadiet",
  "Mikal Bridges",
  "Shai Gilgeous-Alexander",
  "Tyler Kolek",
  "Precious Achiuwa",
  "Isaiah Joe",
  "Aaron Wiggins",
  "Kevin Jr. McCullar",
  "Ousmane Dieng",
  "Tristan da Silva",
  "Caleb Houstan",
  "Anthony Black",
  "Cory Joseph",
  "Jalen Slawson",
  "Jett Howard",
  "Gary Harris",
  "Kelly Oubre Jr.",
  "Guerschon Yabusele",
  "Lonnie Walker IV",
  "Oshae Brissett",
  "Isaiah Mobley",
  "Pete Nance",
  "Adem Bona",
  "Jared McCain",
  "Judah Mintz",
  "Justin Edwards",
  "Nick Richards",
  "Kenyon Martin Jr.",
  "Vasilije Micić",
  "Jusuf Nurkic",
  "Dario Saric",
  "Darius Bazley",
  "Cameron Johnson",
  "Jock Landale",
  "Darius Garland",
  "Jarrett Allen",
  "Evan Mobley",
  "Isaac Okoro",
  "Caris LeVert",
  "Cedi Osman",
  "Kevin Love",
  "Ricky Rubio",
  "Lamar Stevens",
  "Dean Wade",
  "Dylan Windler",
  "Sam Merrill",
  "Koby Altman",
  "Isaiah Hartenstein",
  "Bickerstaff",
  "Cavaliers",
  "JJ Redick",
  "Lebron",
  "Kobe Bryant",
  "Kobe",
  "Shaquille",
  "Shaq",
  "Stephen Curry",
  "Steph",
  "Kevin Durant",
  "Harden",
  "James",
  "Harden",
  "Chris",
  "Michael Jordan",
  "Stephen A. Smith",
  "Kendrick Perkins",
  "Shaquille O'Neal",
  "Charles Barkley",
  "Chris Broussard",
  "Rachel Nichols",
  "Adrian Wojnarowski",
  "Zach Lowe",
  "Brian Windhorst",
  "Marc Stein",
  "Ramona Shelburne",
  "Tim MacMahon",
  "Malika Andrews",
  "Jalen Rose",
  "Jalen",
  "Kenny Smith",
  "Reggie Miller",
  "Mike Breen",
  "Jeff Van Gundy",
  "Mark Jackson",
  "Larry O'Brien",
  "Larry O'Brien Trophy",
  "NBA Finals",
  "NBA Championship",
  "NBA Playoffs",
  "NBA All-Star Game",
  "NBA Draft",
  "NBA Summer League",
  "NBA G League",
  "NBA All-Star Weekend",
  "NBA Awards",
  "NBA MVP",
  "NBA Rookie of the Year",
  "NBA Defensive Player of the Year",
]);

function toSentenceCasePreserveAcronyms(str: string): string {
  const cleaned = str.toLowerCase().replace(/\s+/g, " ").trim();

  const words = cleaned.split(" ").map((word, i, arr) => {
    const upper = word.toUpperCase();

    if (ACRONYMS.has(upper)) return upper;

    // Try to match multi-word proper nouns
    const twoWord =
      i < arr.length - 1 ? `${capitalize(word)} ${capitalize(arr[i + 1])}` : "";
    if (PROPER_NOUNS.has(twoWord)) {
      arr[i + 1] = ""; // remove the next word from processing
      return twoWord;
    }

    const cap = capitalize(word);
    return PROPER_NOUNS.has(cap) ? cap : i === 0 ? cap : word;
  });

  return words.filter(Boolean).join(" ");
}

function capitalize(word: string) {
  return word.charAt(0).toUpperCase() + word.slice(1);
}

export function useHighlights(
  query = "NBA dunks OR game winners OR buzzer beaters OR crossovers OR trending",
  maxResults = 50
) {
  const [highlights, setHighlights] = useState<Highlight[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const cacheKey = `cachedHighlights-${query}-${maxResults}`;

  useEffect(() => {
    const fetchHighlights = async () => {
      setLoading(true);
      setError(null);

      try {
        const cached = await AsyncStorage.getItem(cacheKey);
        if (cached) {
          const cachedData: Highlight[] = JSON.parse(cached);
          setHighlights(cachedData);
          setLoading(false);
        }

        const response = await fetch(
          `https://4e51-132-170-9-79.ngrok-free.app/api/highlights?maxResults=${maxResults}&query=${encodeURIComponent(
            query
          )}`
        );

        if (!response.ok) {
          throw new Error("Failed to fetch highlights");
        }

        const data: Highlight[] = await response.json();

      const cleanedData = data
  .filter(
    (item) =>
      !/tickets|playstation/i.test(item.title) // exclude if title contains those keywords
  )
  .map((item) => ({
    ...item,
    title: toSentenceCasePreserveAcronyms(decodeHTMLEntities(item.title)),
  }));

        // console.log(
        //   "Cleaned Titles:",
        //   cleanedData.map((item) => item.title)
        // );

        setHighlights(cleanedData);
        await AsyncStorage.setItem(cacheKey, JSON.stringify(cleanedData));
      } catch (err: any) {
        setError(err.message);
        if (!highlights.length) setHighlights([]);
      } finally {
        setLoading(false);
      }
    };

    fetchHighlights();
  }, [query, maxResults]);

  return { highlights, loading, error };
}
